name: nb-skdecide-py38
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - cpuonly
  - pytorch==1.10.1
  - pip:
    - matplotlib
    - ipywidgets
    - ipympl
    - nbgitpuller
    - pyvirtualdisplay
    - PyOpenGL-accelerate
    - PyOpenGL
