name: nb-skdecide-py38
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pip:
    - matplotlib
    - ipywidgets
    - ipympl
    - cpuonly
    - torch==1.10.1
    - nbgitpuller
    - pyvirtualdisplay
    - PyOpenGL-accelerate
    - PyOpenGL
