name: nb-skdecide-py38
dependencies:
  - python=3.8
  - pip
  - pip:
    - matplotlib
    - ipywidgets
    - ipympl
    - torch==1.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
    - nbgitpuller
    - pyvirtualdisplay
    - PyOpenGL-accelerate
    - PyOpenGL
