#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====
# No longer install development version, it's included in environment.yml
#pip install -e git+https://github.com/icesat2py/icepyx.git#egg=icepyx --src /srv/icesat2py

NIGHTLY_TAG="nightly"
NIGHTLY_REPO="airbus/scikit-decide"

# Install scikit-decide from last nightly build if not yet installed
skdecide_version=$(pip list | grep "scikit-decide")

echo "Scikit-decide is (${skdecide_version})"

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
