#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====
NIGHTLY_TAG="nightly"
NIGHTLY_REPO="airbus/scikit-decide"

skdecide_version=$(pip list | grep "scikit-decide")

if [ -z "${skdecide_version}" ]; then
  echo "Scikit-decide not found: installing from last nightly build."
  # get last nightly build asset url
  asset_url="$(\
    curl -s https://api.github.com/repos/${NIGHTLY_REPO}/releases \
    | jq -c ".[] | select( .tag_name == \"$NIGHTLY_TAG\" ) | .assets|sort_by(.createdAt)|.[-1].browser_download_url" \
    | sed -e 's/\"//g'
  )"
  # check that it exists (either "null" is no asset in nightly or "" if no tag nightly at all)
  if  [ $asset_url == "null" ] || [ $asset_url == "" ]; then
    echo "No nightly build available. Falling back to last version in pypi."
    pip install scikit-decide"[all]"
  else
    echo "Downloading and installing nightly"
    # download and unzip
    curl --location --output nightly.zip ${asset_url}
    unzip nightly.zip
    # install scikit-decide with all extras
    #pip install --pre --find-links ./dist/ "scikit-decide[all]"
  fi
else
  echo "Scikit-decide (${skdecide_version}) already installed."
fi

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
