#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====
NIGHTLY_TAG="nightly"
NIGHTLY_REPO="airbus/scikit-decide"

skdecide_version=$(pip list | grep "scikit-decide")

if [ -z "${skdecide_version}" ]; then
  echo "Scikit-decide not found: installing from last nightly build."
  # get last nightly build asset url
  asset_url=""
else
  echo "Scikit-decide (${skdecide_version}) already installed."
fi

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
